### PR TITLE
Audiobook

### PR DESCRIPTION
**Pull request by Mastermind-sap**
Created an audiobook. 
This 7 lines python code speaks out whatever is written in the text file "book.txt". 
Modules Required: pyttsx3
Please review my PR @xiaowuc2

### CODE REVIEW

**Comment by xiaowuc2** [comment]
Nice one, I'll check the code and add some more changes on readme.md.

**Comment by Mastermind-sap** [comment]
ok cool :+1:

**Comment by Mastermind-sap** [comment]
Any update @xiaowuc2 ?

**Comment by xiaowuc2** [comment]
Sorry I'll merge it tomorrow 👍🏻

**Comment by Mastermind-sap** [comment]
> Sorry I'll merge it tomorrow 👍🏻

ok 👍

**Comment by Mastermind-sap** [comment]
@xiaowuc2 should i close this pr?

**Comment by xiaowuc2** [comment]
No, I've merged it already :)
Do you love Mathematics ?

**Comment by Mastermind-sap** [comment]
yes, i do love maths :smile:  @xiaowuc2

**Comment by xiaowuc2** [comment]
Then join @qxresearch/mathematics we're doing some projects @Mastermind-sap

**Comment by Mastermind-sap** [comment]
sure :+1: @xiaowuc2

**Pull request merged**
